[build]
  publish = ".next"
  functions = "functions/"
  command = "pnpm run build"

[context.deploy-preview]
  command = "pnpm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://social.thesonofthomp.com/"
  to = "https://thesonofthomp.com/social"
  status = 200
  force = true
