[build]
  base = "."
  publish = "out/"
  functions = "functions/"
  command = "turbo run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://social.thesonofthomp.com/"
  to = "https://thesonofthomp.com/social"
  status = 200
  force = true