[build]
  publish = "out/"
  functions = "functions/"
  command = "npm run build"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "https://social.thesonofthomp.com/"
  to = "https://thesonofthomp.com/social"
  status = 200
  force = true