[build]
  publish = "out/"
  functions = "functions/"
  command = "npm run build"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = “/social/”
  to = “https://social.example.com/
  status = 200
  force = true