[build]
  publish = "apps/web/.next"
  functions = "apps/web/functions/"
  command = "turbo build --force"

[build.environment]
  # Load environment variables from root .env file for the build process
  NODE_OPTIONS = "--max_old_space_size=4096"

[context.deploy-preview]
  command = "turbo build --force"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://social.thesonofthomp.com/"
  to = "https://thesonofthomp.com/social"
  status = 200
  force = true