[build]
  publish = "apps/web/.next"
  functions = "apps/web/functions/"
  command = "turbo build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://social.thesonofthomp.com/"
  to = "https://thesonofthomp.com/social"
  status = 200
  force = true